### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by cehsu** [sfbrigade/sfsbook#149]
This is apparently a crucial feature for the volunteers. What are some ideas for implementing this?

**Comment by MosesSupposes** [comment]
I know that HTML5 has a new offline persistent data storage API: (https://www.html5rocks.com/en/tutorials/offline/whats-offline/); also PWA's fundamentally have an offline-first orientation: (https://www.youtube.com/watch?v=cmGr0RszHc8)

**Comment by sent-hil** [comment]
Hi @cehsu! I was thinking something as simple as returning the json as part of html payload and iterating via some basic data structures. So a data structure like:
```
var data = {
  uuid_1: { name: ... },
  uuid_2: { name: ... }
}

var indexes = {
   location: { berkeley : [] }
   ....
}
```

And in the search we just iterate through the indexes for categories. For plain text search we can just loop over all the entries. Since it's just 300kb of data it shouldn't be too slow methinks.

Optionally we can use something like http://elasticlunr.com/example/index.html or some plugin out there which I'm sure will be good enough.

**Comment by sent-hil** [comment]
On second thought let's just use elasticlunr, it's <10kb compressed, has no deps and supports some pretty advanced search features; almost equivalent to bleve I think. So in total we'll send 300-350kb extra payload on each request and need to change the ui when an user searches, but that should satisfy your reqs.

**Comment by cehsu** [comment]
Poking around @syu15's comments in helpers, it looks like elasticlunr might not support multiple search terms? if that is the case, should we look into something like js-search, which does? I will report back with more information on how SFWAR volunteers use search terms as filters.
