### ISSUE TITLE
Invite system

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#37]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: We need an invite system that allows existing signed in volunteer users to generate a unique URL to invite other volunteers to create an account. This unique URL will be the only way new users accounts can be created (except by admins)

**Comment by rjkroege** [comment]
Sub-systems

*  generate the (crypto) value for the url. something like: `https://sfsbook.org/join/3593837558/index.html`
*  write key, inviter data, date to database table `invites`
*  produce pretty screen featuring url, instructions
*  optional feature: QR code?
*  need router support to parse URL
*  look up the invite key in the `invites`. If valid, take the person browsing it to the "create an account" page. (See issue of how to manage accounts) Otherwise, indicate auth issue
*  update the `invites` table as being rrsp-ed
*  keep all `invites` for auditing?
